package edu.pse.beast.codearea.codeinput;

import javax.swing.JScrollPane;

/**
 * The tests for JTextPane frames.
 *
 * @author Holger Klein
 */
public final class JTextPaneTestFrame extends javax.swing.JFrame {
    /** The Constant PREFERRED_SIZE_88. */
    private static final int PREFERRED_SIZE_88 = 88;
    /** The Constant PREFERRED_SIZE_201. */
    private static final int PREFERRED_SIZE_201 = 201;
    /** The Constant PREFERRED_SIZE_380. */
    private static final int PREFERRED_SIZE_380 = 380;

    private static final long serialVersionUID = 1L;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** A scroll pane instance. */
    private javax.swing.JScrollPane jScrollPane1;
    /** A text pane instance. */
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form JTextPaneTestFrame.
     */
    public JTextPaneTestFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jScrollPane1.setViewportView(jTextPane1);

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup().addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                      PREFERRED_SIZE_380, Short.MAX_VALUE)
                        .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup().addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                      PREFERRED_SIZE_201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(PREFERRED_SIZE_88, Short.MAX_VALUE)));
        pack();
    } // </editor-fold>//GEN-END:initComponents

    public javax.swing.JTextPane getTextPane() {
        return jTextPane1;
    }

    public JScrollPane getScrollPane() {
        return jScrollPane1;
    }
}
