/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.pse.beast.options;

import edu.pse.beast.saverloader.OptionSaverLoader.OptionsSaverLoaderInterface;
import edu.pse.beast.stringresource.StringResourceLoader;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Holger-Desktop
 */
public class OptionPresenterFrame extends javax.swing.JFrame {

    private StringResourceLoader srl;
    private Options opt;
    /**
     * Creates new form OptionPresenterFrame
     */
    public OptionPresenterFrame(Options opt, StringResourceLoader srl) {
        initComponents();
        this.opt = opt;
        this.srl = srl;
        setTitle(srl.getStringFromID(opt.getId()));
        jButton1.setText(srl.getStringFromID("ok_button"));
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        showOptionsRec(opt);
        jButton1.addActionListener((ae) -> {
            opt.reapply();
            OptionsSaverLoaderInterface.saveOpt(opt);
            this.dispose();
        });
    }
    
    private void showOptionsRec(Options opt) {
        for(Options subOpt : opt.getSubOptions()) {
            JPanel panel = new JPanel();
            
            for(OptionElement elem : subOpt.getOptionElements()) {
                JLabel label = new JLabel(srl.getStringFromID(elem.getID()));
                OptionElemComboBox combobox = new OptionElemComboBox(elem);
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
                for(String s : elem.getChoosableOptions()) {
                    try {
                        model.addElement(srl.getStringFromID(s));
                    } catch (Exception e) {
                        model.addElement(s);
                    }                    
                }
                try {
                    model.setSelectedItem(srl.getStringFromID(elem.getChosenOption()));
                } catch (Exception e) {
                    model.setSelectedItem(elem.getChosenOption());
                } 
                combobox.setModel(model);
                
                
                combobox.addItemListener((ie) -> {
                    ((OptionElemComboBox)ie.getSource()).getElem().handleSelection(srl.getIdForString((String)ie.getItem()));
                });
                
                panel.add(label);
                panel.add(combobox);                
            }
            
            jTabbedPane1.add(srl.getStringFromID(subOpt.getId()) ,panel);
            showOptionsRec(subOpt);            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 338, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }    

    public JButton getjButton1() {
        return jButton1;
    }
    
    
}
