package edu.pse.beast.gui.errors;

public enum BeastErrorTypes {
    NOT_IMPLEMENTED_CODE_PATH, NOT_ALL_LOOPS_DESCRIBED, IO_ERROR,
    CBMC_VAR_NAME_ALREADY_EXISTS, ERROR_WHEN_SAVING_ALL, DUPLICATE_C_FUNC_NAME,
    CANT_REMOVE_VOTING_FUNCTION

}
