package edu.pse.beast.api.c_parser;

public enum CLoopParseResultType {
	NO_CONDITIONAL_STATEMENT,
	CONDITIONAL_STATEMENT_NOT_RIGHT_FORM,
	CONDITIONAL_STATEMENT_NOT_LESS, 
	PROBABLE_SUCCESS_CONSTANT_LOOP
}
